/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.cjme.motorphsystem.controller;

/**
 *
 * @author MYS
 */
public class LeaveDialog extends javax.swing.JDialog {

    /**
     * Creates new form LeaveDialog
     * @param parent
     * @param modal
     */
    public LeaveDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LeavePanel = new javax.swing.JPanel();
        LeaveAppFormLabel = new javax.swing.JLabel();
        LeaveTopPanel = new javax.swing.JPanel();
        LeaveTypeLabel = new javax.swing.JLabel();
        LNumberofDaysLabel = new javax.swing.JLabel();
        LeaveTypeComboBox = new javax.swing.JComboBox<>();
        LNumberofDaysTextBox = new javax.swing.JTextField();
        LeaveReasonScrolPane = new javax.swing.JScrollPane();
        LeaveReasonTextArea = new javax.swing.JTextArea();
        LeaveReasonLabel = new javax.swing.JLabel();
        LeaveSubPanel = new javax.swing.JPanel();
        LeaveCancelButton = new javax.swing.JButton();
        SubmitLeaveRequestButton = new javax.swing.JButton();
        LeaveStartDatePanel = new javax.swing.JPanel();
        LeaveStartDateLabel = new javax.swing.JLabel();
        LeaveStartDateCalendar = new com.toedter.calendar.JCalendar();
        LeaveEndDatePanel = new javax.swing.JPanel();
        LeaveEndDateLabel = new javax.swing.JLabel();
        LeaveEndDateCalendar = new com.toedter.calendar.JCalendar();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(750, 400));
        setModal(true);
        setResizable(false);

        LeaveAppFormLabel.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        LeaveAppFormLabel.setText("Leave Application Form");

        javax.swing.GroupLayout LeavePanelLayout = new javax.swing.GroupLayout(LeavePanel);
        LeavePanel.setLayout(LeavePanelLayout);
        LeavePanelLayout.setHorizontalGroup(
            LeavePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LeavePanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(LeaveAppFormLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        LeavePanelLayout.setVerticalGroup(
            LeavePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LeavePanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(LeaveAppFormLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        LeaveTypeLabel.setText("Leave Type:");

        LNumberofDaysLabel.setText("Number of Days:");

        LeaveTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        LNumberofDaysTextBox.setText("Read Only");

        LeaveReasonTextArea.setColumns(20);
        LeaveReasonTextArea.setRows(5);
        LeaveReasonScrolPane.setViewportView(LeaveReasonTextArea);

        LeaveReasonLabel.setText("Reason:");

        javax.swing.GroupLayout LeaveTopPanelLayout = new javax.swing.GroupLayout(LeaveTopPanel);
        LeaveTopPanel.setLayout(LeaveTopPanelLayout);
        LeaveTopPanelLayout.setHorizontalGroup(
            LeaveTopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LeaveTopPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(LeaveTopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LNumberofDaysLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LeaveTypeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(LeaveTopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LeaveTypeComboBox, 0, 140, Short.MAX_VALUE)
                    .addComponent(LNumberofDaysTextBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addComponent(LeaveReasonLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LeaveReasonScrolPane, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        LeaveTopPanelLayout.setVerticalGroup(
            LeaveTopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LeaveTopPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LeaveTopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LeaveTopPanelLayout.createSequentialGroup()
                        .addGroup(LeaveTopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LeaveTypeLabel)
                            .addComponent(LeaveTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LeaveReasonLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(LeaveTopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LNumberofDaysLabel)
                            .addComponent(LNumberofDaysTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(LeaveReasonScrolPane, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        LeaveCancelButton.setText("Cancel");

        SubmitLeaveRequestButton.setBackground(new java.awt.Color(51, 102, 255));
        SubmitLeaveRequestButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        SubmitLeaveRequestButton.setForeground(new java.awt.Color(255, 255, 255));
        SubmitLeaveRequestButton.setText("Submit Leave Request");

        javax.swing.GroupLayout LeaveSubPanelLayout = new javax.swing.GroupLayout(LeaveSubPanel);
        LeaveSubPanel.setLayout(LeaveSubPanelLayout);
        LeaveSubPanelLayout.setHorizontalGroup(
            LeaveSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LeaveSubPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LeaveCancelButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SubmitLeaveRequestButton)
                .addGap(43, 43, 43))
        );
        LeaveSubPanelLayout.setVerticalGroup(
            LeaveSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LeaveSubPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LeaveSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LeaveCancelButton)
                    .addComponent(SubmitLeaveRequestButton))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        LeaveStartDateLabel.setText("Start Date:");

        javax.swing.GroupLayout LeaveStartDatePanelLayout = new javax.swing.GroupLayout(LeaveStartDatePanel);
        LeaveStartDatePanel.setLayout(LeaveStartDatePanelLayout);
        LeaveStartDatePanelLayout.setHorizontalGroup(
            LeaveStartDatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LeaveStartDatePanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(LeaveStartDatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LeaveStartDateLabel)
                    .addComponent(LeaveStartDateCalendar, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        LeaveStartDatePanelLayout.setVerticalGroup(
            LeaveStartDatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LeaveStartDatePanelLayout.createSequentialGroup()
                .addComponent(LeaveStartDateLabel)
                .addGap(18, 18, 18)
                .addComponent(LeaveStartDateCalendar, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                .addContainerGap())
        );

        LeaveEndDateLabel.setText("End Date:");

        javax.swing.GroupLayout LeaveEndDatePanelLayout = new javax.swing.GroupLayout(LeaveEndDatePanel);
        LeaveEndDatePanel.setLayout(LeaveEndDatePanelLayout);
        LeaveEndDatePanelLayout.setHorizontalGroup(
            LeaveEndDatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LeaveEndDatePanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(LeaveEndDatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LeaveEndDateLabel)
                    .addComponent(LeaveEndDateCalendar, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        LeaveEndDatePanelLayout.setVerticalGroup(
            LeaveEndDatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LeaveEndDatePanelLayout.createSequentialGroup()
                .addComponent(LeaveEndDateLabel)
                .addGap(18, 18, 18)
                .addComponent(LeaveEndDateCalendar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(LeavePanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(LeaveTopPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(LeaveStartDatePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(LeaveEndDatePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(LeaveSubPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(LeavePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LeaveTopPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LeaveStartDatePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LeaveEndDatePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LeaveSubPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getAccessibleContext().setAccessibleParent(this);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LeaveDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LeaveDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LeaveDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LeaveDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                LeaveDialog dialog = new LeaveDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LNumberofDaysLabel;
    private javax.swing.JTextField LNumberofDaysTextBox;
    private javax.swing.JLabel LeaveAppFormLabel;
    private javax.swing.JButton LeaveCancelButton;
    private com.toedter.calendar.JCalendar LeaveEndDateCalendar;
    private javax.swing.JLabel LeaveEndDateLabel;
    private javax.swing.JPanel LeaveEndDatePanel;
    private javax.swing.JPanel LeavePanel;
    private javax.swing.JLabel LeaveReasonLabel;
    private javax.swing.JScrollPane LeaveReasonScrolPane;
    private javax.swing.JTextArea LeaveReasonTextArea;
    private com.toedter.calendar.JCalendar LeaveStartDateCalendar;
    private javax.swing.JLabel LeaveStartDateLabel;
    private javax.swing.JPanel LeaveStartDatePanel;
    private javax.swing.JPanel LeaveSubPanel;
    private javax.swing.JPanel LeaveTopPanel;
    private javax.swing.JComboBox<String> LeaveTypeComboBox;
    private javax.swing.JLabel LeaveTypeLabel;
    private javax.swing.JButton SubmitLeaveRequestButton;
    // End of variables declaration//GEN-END:variables
}
