/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.cjme.motorphsystem.controller;

/**
 *
 * @author USER
 */
public class Login extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Login.class.getName());

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JPanel LogPanel = new javax.swing.JPanel();
        WelcomeBack = new javax.swing.JPanel();
        Welcome = new javax.swing.JLabel();
        LoginWithGoogle = new javax.swing.JPanel();
        GoogleLogin = new javax.swing.JButton();
        CredentialBars = new javax.swing.JPanel();
        EmailAdd = new javax.swing.JPanel();
        EmailAddTextField = new javax.swing.JTextField();
        EmailAddLabel = new javax.swing.JLabel();
        Password = new javax.swing.JPanel();
        PasswordLabel = new javax.swing.JLabel();
        PasswordField = new javax.swing.JPasswordField();
        RememberMe = new javax.swing.JPanel();
        RememberCheckBox = new javax.swing.JCheckBox();
        ForgotPassword = new javax.swing.JLabel();
        Login = new javax.swing.JPanel();
        LoginButton = new javax.swing.JButton();
        SignUp = new javax.swing.JPanel();
        NoAccountSignUp = new javax.swing.JLabel();
        DesignPanel = new javax.swing.JPanel();
        MotorPHLoginDesign = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        LogPanel.setPreferredSize(new java.awt.Dimension(420, 342));

        WelcomeBack.setPreferredSize(new java.awt.Dimension(400, 100));

        Welcome.setFont(new java.awt.Font("Raleway", 1, 32)); // NOI18N
        Welcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Welcome.setText("Welcome Back!");

        javax.swing.GroupLayout WelcomeBackLayout = new javax.swing.GroupLayout(WelcomeBack);
        WelcomeBack.setLayout(WelcomeBackLayout);
        WelcomeBackLayout.setHorizontalGroup(
            WelcomeBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WelcomeBackLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Welcome, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        WelcomeBackLayout.setVerticalGroup(
            WelcomeBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WelcomeBackLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(Welcome, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        LogPanel.add(WelcomeBack);

        LoginWithGoogle.setPreferredSize(new java.awt.Dimension(300, 50));

        GoogleLogin.setText("Log In with Google");
        GoogleLogin.setToolTipText("");
        GoogleLogin.setIconTextGap(10);
        GoogleLogin.setMargin(new java.awt.Insets(2, 15, 4, 15));
        GoogleLogin.setPreferredSize(new java.awt.Dimension(250, 30));
        GoogleLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoogleLoginActionPerformed(evt);
            }
        });
        LoginWithGoogle.add(GoogleLogin);

        LogPanel.add(LoginWithGoogle);

        CredentialBars.setPreferredSize(new java.awt.Dimension(400, 120));

        EmailAdd.setPreferredSize(new java.awt.Dimension(300, 50));
        EmailAdd.setLayout(new java.awt.BorderLayout(4, 4));

        EmailAddTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailAddTextFieldActionPerformed(evt);
            }
        });
        EmailAdd.add(EmailAddTextField, java.awt.BorderLayout.CENTER);

        EmailAddLabel.setText("Email Address:");
        EmailAdd.add(EmailAddLabel, java.awt.BorderLayout.PAGE_START);

        CredentialBars.add(EmailAdd);

        Password.setPreferredSize(new java.awt.Dimension(300, 50));
        Password.setLayout(new java.awt.BorderLayout(4, 4));

        PasswordLabel.setText("Password:");
        Password.add(PasswordLabel, java.awt.BorderLayout.PAGE_START);
        Password.add(PasswordField, java.awt.BorderLayout.CENTER);

        CredentialBars.add(Password);

        LogPanel.add(CredentialBars);

        RememberMe.setPreferredSize(new java.awt.Dimension(300, 20));
        RememberMe.setLayout(new java.awt.BorderLayout());

        RememberCheckBox.setText("Remember Me");
        RememberCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RememberCheckBoxActionPerformed(evt);
            }
        });
        RememberMe.add(RememberCheckBox, java.awt.BorderLayout.WEST);

        ForgotPassword.setForeground(new java.awt.Color(255, 102, 102));
        ForgotPassword.setText("Forgot Password?");
        RememberMe.add(ForgotPassword, java.awt.BorderLayout.EAST);

        LogPanel.add(RememberMe);

        Login.setPreferredSize(new java.awt.Dimension(300, 50));

        LoginButton.setBackground(new java.awt.Color(255, 51, 51));
        LoginButton.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        LoginButton.setForeground(new java.awt.Color(255, 255, 255));
        LoginButton.setText("Log In");
        LoginButton.setPreferredSize(new java.awt.Dimension(250, 40));
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });
        Login.add(LoginButton);

        LogPanel.add(Login);

        SignUp.setPreferredSize(new java.awt.Dimension(300, 100));

        NoAccountSignUp.setText("Don`t Have Account Yet? Sign Up");
        SignUp.add(NoAccountSignUp);

        LogPanel.add(SignUp);

        getContentPane().add(LogPanel, java.awt.BorderLayout.WEST);

        DesignPanel.setBackground(new java.awt.Color(255, 255, 255));
        DesignPanel.setToolTipText("");
        DesignPanel.setAutoscrolls(true);
        DesignPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        DesignPanel.setMaximumSize(new java.awt.Dimension(525, 525));
        DesignPanel.setMinimumSize(new java.awt.Dimension(100, 50));
        DesignPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));

        MotorPHLoginDesign.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/MotorPH Login 525 x 525.png"))); // NOI18N
        DesignPanel.add(MotorPHLoginDesign);

        getContentPane().add(DesignPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GoogleLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoogleLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GoogleLoginActionPerformed

    private void EmailAddTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailAddTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailAddTextFieldActionPerformed

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LoginButtonActionPerformed

    private void RememberCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RememberCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RememberCheckBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Login().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CredentialBars;
    private javax.swing.JPanel DesignPanel;
    private javax.swing.JPanel EmailAdd;
    private javax.swing.JLabel EmailAddLabel;
    private javax.swing.JTextField EmailAddTextField;
    private javax.swing.JLabel ForgotPassword;
    private javax.swing.JButton GoogleLogin;
    private javax.swing.JPanel Login;
    private javax.swing.JButton LoginButton;
    private javax.swing.JPanel LoginWithGoogle;
    private javax.swing.JLabel MotorPHLoginDesign;
    private javax.swing.JLabel NoAccountSignUp;
    private javax.swing.JPanel Password;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JLabel PasswordLabel;
    private javax.swing.JCheckBox RememberCheckBox;
    private javax.swing.JPanel RememberMe;
    private javax.swing.JPanel SignUp;
    private javax.swing.JLabel Welcome;
    private javax.swing.JPanel WelcomeBack;
    // End of variables declaration//GEN-END:variables
}
